### PR TITLE
Upgraded gradle to 2.7 and rxjava-project plugin to 3.0.0

### PR DESCRIPTION
**Pull request by jpenglert**
Fixed the build by upgrading gradle, rxjava-project plugin, and applying the java plugin

### CODE REVIEW

**Comment by thomasnield** [comment]
It looks like there are still some build issues 

```
The command "eval ./gradlew assemble" failed. Retrying, 2 of 3.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'rxjavafx'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.netflix.nebula:nebula-release-plugin:3.+.
     Required by:
         :rxjavafx:1.0.0-RC1-SNAPSHOT > com.netflix.nebula:gradle-rxjava-project-plugin:3.0.0
      > Could not resolve com.netflix.nebula:nebula-release-plugin:3.1.0.
         > Could not parse POM https://plugins.gradle.org/m2/com/netflix/nebula/nebula-release-plugin/3.1.0/nebula-release-plugin-3.1.0.pom
            > Unable to resolve version for dependency 'com.jfrog.bintray.gradle:gradle-bintray-plugin:jar'
```

**Comment by jpenglert** [comment]
Strange. Built successfully on my local machine using "./gradlew.bat assemble". Looks like the following POM:

https://plugins.gradle.org/m2/com/netflix/nebula/nebula-release-plugin/3.1.0/nebula-release-plugin-3.1.0.pom

is missing a "<version>" element for the "gradle-bintray-plugin" dependency.

**Comment by thomasnield** [comment]
Can you fix it? I know little about the Nebula plugin and I could only get my fork to build without it. @benjchristensen advises to use however it as discussed in #3. If you could get this up and running, myself and others would be very grateful.

**Comment by jpenglert** [comment]
I don't know much about the Nebula plugins either or how to test the CI (travis) build locally in order to repro the problem. I will try to find time to work on this in the near future but may end up writing my own JavaFXScheduler instead of fighting with these build issues just to use a few small classes. This project seems so close to being usable...too bad the Netflix support went away.

**Comment by thomasnield** [comment]
I agree I'd like to get this up and running with as little hassle as possible so we can get it to Maven Central. I just have not had time to investigate the build automation surrounding this. But I'll try and investigate this version number issue (hopefully its super easy, that would be swell). 

For now, my fork with a hack-job of a Gradle script is working if you'd like to use it. 
https://github.com/thomasnield/RxJavaFX/blob/0.x/build.gradle

**Comment by thomasnield** [comment]
I believe I have write rights to this repo so we will see what we can work out carefully.

**Comment by thomasnield** [comment]
I got the build fixed on my PR, and the Nebula dependency is now in working order. Just cant figure out one silly unit test failing in Travis.

**Comment by thomasnield** [comment]
See #9

**Pull request closed without merging**
