### PR TITLE
The project was adapted to RxJava v3.0.1

### PR DESCRIPTION
**Pull request by pvnhome**
The project was adapted to RxJava v3.0.1 and successfully tested.

### CODE REVIEW

**Comment by Speljohan** [comment]
Any chance you could add this to Maven central repository so that i can make use of it before the PR is accepted? I'm trying to avoid cluttering my project with more source modules than i have to.

Thanks in advance, and great work!

**Comment by pvnhome** [comment]
I use it from my local Maven and Ivy repositories :-(

**Comment by Speljohan** [comment]
> I use it from my local Maven and Ivy repositories :-(

This would have been fine for me as well, but unfortunately my project  has several team members, so It's not an ideal solution :/

**Comment by thomasnield** [comment]
I missed this memo, sorry. I will get on this right now.

**Comment by Speljohan** [comment]
Thanks, I appreciate it :)

**Comment by thomasnield** [comment]
I am confused by the deployment error: 

```
could not upload to 'https://api.bintray.com/content/reactivex/RxJava/RxJavaFX/RxJavaFX/io/reactivex/rxjava3/rxjavafx/3.0.0/rxjavafx-3.0.0-sources.jar': HTTP/1.1 403 Forbidden [message:Version 'RxJavaFX' has been published for more than 365 days. Files can only be uploaded to a version within 365 days from its publish date.]
```

**Comment by Speljohan** [comment]
This looks like an artificial limitation in the Rest API for Bintray.

> Optionally publishing the uploaded artifact(s) as part of uploading (off by default). Additional content can be uploaded to a published version within 365 days from its publish date.

From some googling, it looks like this can be resolved in a variety of ways, ranging from deleting the version to using an update command that bumps the version instead.

**Comment by Speljohan** [comment]
I've taken the liberty of creating a Bintray account and publishing a snapshot of the current github repository in case anyone wants to use it in their projects with maven. It can be found here:
https://bintray.com/speljohan/rxjavafx-mirror

I've never used bintray before, but i think i set it up correctly. If not, let me know!

**Comment by thomasnield** [comment]
@Speljohan would it be okay if I made you a collaborator? At this point I need to share ownership with someone since I'm busy with some other initiatives.

**Comment by Speljohan** [comment]
I can't promise any huge commitment due to my life situation, but I'll do what i can!

**Comment by thomasnield** [comment]
Thank you, I'm kind of in the same boat. If we can recruit other folks to help I am all for that. My bandwidth is strained now and my work has been changing in nature a lot.

I'll see if I can subscribe to get notifications at least.

**Comment by Speljohan** [comment]
I'll at the the very least get the automatic gradle builds back up and running and add RxJava 3 support. Maybe we can get it more coherently organized using GitHub Projects?

**Comment by thomasnield** [comment]
@Speljohan sounds good to me. Thanks for creating the Projects page.

**Comment by Soamid** [comment]
Sorry for digging up an old issue, but it seems the snapshot on Bintray doesn't work anymore (because Bintray is gone). :( Is there any chance of uploading this artifact into Maven Central? I've used this lib both in my team's project and for educational purposes with my students so having a flexible gradle/maven project is really useful for me.

**Comment by thomasnield** [comment]
Hi folks, I'm too busy to maintain any projects I'm not dogfooding for my own work nowadays. Feel free to fork this and get this rolling under another domain.

**Comment by torakiki** [comment]
I forked it and released under a different package here https://github.com/torakiki/RxJavaFX
It's to make it easily available to my projects so I'm not going to maintain it but maybe others find it useful

**Comment by Soamid** [comment]
Thank you for taking care of this! :) Btw, for some reason, your homepage link in Maven Central is wrong. Anyways, thanks!

**Comment by torakiki** [comment]
Ah, yes, I fixed that, thanks.

**Comment by thomasnield** [comment]
Hi @torakiki, thank you for supporting this! It's really appreciated. Wish I could still help but life's changing priorities in what I can spend time on. 

I will update the README to let people know you have the best alternative fork now.

**Pull request merged**
