### PR TITLE
FxCollections Interop

### PR DESCRIPTION
**Pull request by thomasnield**
Exploration of interoperating RxJava with `ObservableList` and other collections has proven to have utility. See #26

### CODE REVIEW

**Comment by thomasnield** [comment]
If anybody has inputs on how the API methods are named, please let me know as this will probably become tangible quickly. 

I think I'm going to add the following methods to the `JavaFxObservable` factory. These are the proposed method signatures which I will probably refactor things to. Let me know if you guys have any thoughts. 

``` java
//emits entire ObservableList<T> every time it changes
public static <T> Observable<ObservableList<T>> fromObservableList(ObservableList<T> observableList)

//Emits each ListChange<T>, with value and ADDED/REMOVED flag, every time ObservableList is modified
public static <T> Observable<ListChange<T>> fromObservableListChanges(ObservableList<T> observableList)

//Emits each distinct ListChange, with value and ADDED/REMOVED flag, every time ObservableList is modified
public static <T> Observable<ListChange<T>> fromObservableListDistinctChanges(ObservableList<T> observableList)

//Emits each distinct mapped value as a ListChange, with value and ADDED/REMOVED flag, every time source ObservableList is modified
public static <T,R> Observable<ListChange<R>> fromObservableListDistinctChanges(ObservableList<T> observableList, Func1<T,R> valueMapper)

```

This could open up some possibilities to create reactive implementations of `ObservableList`, such as a `DistinctObservableList` that reacts to a source `ObservableList` and maintains a distinct list of mapped values derived from it. I really wish I had something like this when I built the [TableFilter for the ControlsFX project](http://fxexperience.com/2016/03/introducing-the-controlsfx-tablefilter/), which provides an Excel-like filter for a TableView.

**Comment by thomasnield** [comment]
Should the fourth factory return a `ListChange<T>` rather than a `ListChange<R>`? This might make the factory a bit more flexible and allow deciding on how the distinct value is used. 

``` java
//Emits each value as a ListChange, with value and ADDED/REMOVED flag, using a distinct value mapper every time source ObservableList is modified
public static <T,R> Observable<ListChange<T>> fromObservableListDistinctChanges(ObservableList<T> observableList, Func1<T,R> valueMapper)
```

**Comment by thomasnield** [comment]
After some reflection, I think having custom implementations of `ObservableList` might be more appropriate for [ReactFX](https://github.com/TomasMikula/ReactFX). As far as I can see the goal of this library is to make RxJava compatible with JavaFX, by turning JavaFX events into Observables (and vice versa). It is not to improve JavaFX and augment its functionality which ReactFX is already doing. Adding new functionality that is specific to JavaFX deviates from the interoperability goal. 

However, the proposed factories still seem appropriate, as there is a need to turn `ObservableList` events into `Observables`.

**Comment by manuel-mauky** [comment]
I think the `fromObservableListChanges` shouldn't only check on `wasRemoved` and `wasAdded` but also on `wasUpdated`. You could even add a `fromObservableListUpdates` equivalent to `fromObservableListAdds` and `fromObservableListRemovals`. 

See the following example for when `wasUpdated` is triggered:

``` java
public class User {
    private StringProperty name = new SimpleStringProperty();
    public StringProperty nameProperty() {
        return name;
    }
}

ObservableList<User> users = FXCollections.observableArrayList(user -> new Observable[]{user.nameProperty()});

User user = new User();
users.add(user);

user.nameProperty().setValue("manuel"); // this will trigger an update event
```

The lambda that is passed to the `FXCollections.observableArrayList` factory method tells the observale list which properties are relevent for update events. 
I think this is a less known feature of observableLists but it can be really handy in some situations.

**Comment by thomasnield** [comment]
Wow I was not aware of this feature. This definitely deserves a factory as well, and a ListChange category. I'll play with this and come up with a fully implemented PR.

**Comment by thomasnield** [comment]
Alright @lestard here is my full proposed implementation. These will be callable from the `JavaFxObservable` factory. I also put in some optimizations using a `HashMap` to manage distinct emissions. Let me know what you think. 

``` java

public final class ObservableListSource {

    public static <T> Observable<ObservableList<T>> fromObservableList(final ObservableList<T> source) {

        return Observable.create((Observable.OnSubscribe<ObservableList<T>>) subscriber -> {

            source.addListener((ListChangeListener<T>) c -> {
                subscriber.onNext(source);
            });
        }).subscribeOn(JavaFxScheduler.getInstance());
    }

    public static <T> Observable<T> fromObservableListAdds(final ObservableList<T> source) {

        return Observable.create((Observable.OnSubscribe<T>) subscriber -> {

            ListChangeListener<T> listener = c -> {
                while (c.next()) {
                    if (c.wasAdded()) {
                        c.getAddedSubList().forEach(subscriber::onNext);
                    }
                }
            };
            source.addListener(listener);
            subscriber.add(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> source.removeListener(listener)));

        }).subscribeOn(JavaFxScheduler.getInstance());
    }
    public static <T> Observable<T> fromObservableListRemovals(final ObservableList<T> source) {

        return Observable.create((Observable.OnSubscribe<T>) subscriber -> {

            ListChangeListener<T> listener = c -> {
                while (c.next()) {
                    if (c.wasRemoved()) {
                        c.getRemoved().forEach(subscriber::onNext);
                    }
                }
            };

            source.addListener(listener);
            subscriber.add(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> source.removeListener(listener)));

        }).subscribeOn(JavaFxScheduler.getInstance());
    }
    public static <T> Observable<T> fromObservableListUpdates(final ObservableList<T> source) {

        return Observable.create((Observable.OnSubscribe<T>) subscriber -> {

            ListChangeListener<T> listener = c -> {
                while (c.next()) {
                    if (c.wasUpdated()) {
                        for (int i = c.getFrom(); i < c.getTo(); i++) {
                            subscriber.onNext(c.getList().get(i));
                        }
                    }
                }
            };
            source.addListener(listener);
            subscriber.add(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> source.removeListener(listener)));

        }).subscribeOn(JavaFxScheduler.getInstance());
    }
    public static <T> Observable<ListChange<T>> fromObservableListChanges(final ObservableList<T> source) {
        return Observable.create((Observable.OnSubscribe<ListChange<T>>) subscriber -> {

            ListChangeListener<T> listener = c -> {
                while (c.next()) {
                    if (c.wasAdded()) {
                        c.getAddedSubList().forEach(v -> subscriber.onNext(ListChange.of(v,Flag.ADDED)));
                    }
                    if (c.wasRemoved()) {
                        c.getRemoved().forEach(v -> subscriber.onNext(ListChange.of(v,Flag.REMOVED)));
                    }
                    if (c.wasUpdated()) {
                        for (int i = c.getFrom(); i < c.getTo(); i++) {
                            subscriber.onNext(ListChange.of(c.getList().get(i),Flag.UPDATED));
                        }
                    }
                }
            };
            source.addListener(listener);

            subscriber.add(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> source.removeListener(listener)));
        }).subscribeOn(JavaFxScheduler.getInstance());
    }

    public static <T> Observable<ListChange<T>> fromObservableListDistinctChanges(final ObservableList<T> source) {

        return Observable.create((Observable.OnSubscribe<ListChange<T>>) subscriber -> {

            final DupeCounter<T> dupeCounter = new DupeCounter<>();
            source.stream().forEach(dupeCounter::add);

            source.addListener((ListChangeListener<T>) c -> {

                while (c.next()) {
                    if (c.wasAdded()) {
                        c.getAddedSubList().stream().filter(v -> dupeCounter.add(v) == 1)
                                .forEach(v -> subscriber.onNext(ListChange.of(v,Flag.ADDED)));
                    }
                    if (c.wasRemoved()) {
                        c.getRemoved().stream().filter(v -> dupeCounter.remove(v) == 0)
                                .forEach(v -> subscriber.onNext(ListChange.of(v,Flag.REMOVED)));
                    }
                }
            });
        }).subscribeOn(JavaFxScheduler.getInstance());
    }
    public static <T,R> Observable<ListChange<T>> fromObservableListDistinctChanges(final ObservableList<T> source, Func1<T,R> mapper) {

        return Observable.create((Observable.OnSubscribe<ListChange<T>>) subscriber -> {

            final DupeCounter<R> dupeCounter = new DupeCounter<>();
            source.stream().map(mapper::call).forEach(dupeCounter::add);

            source.addListener((ListChangeListener<T>) c -> {

                while (c.next()) {
                    if (c.wasAdded()) {
                        c.getAddedSubList().stream().filter(v -> dupeCounter.add(mapper.call(v)) == 1)
                                .forEach(v -> subscriber.onNext(ListChange.of(v,Flag.ADDED)));
                    }
                    if (c.wasRemoved()) {
                        c.getRemoved().stream().filter(v -> dupeCounter.remove(mapper.call(v)) == 0)
                                .forEach(v -> subscriber.onNext(ListChange.of(v,Flag.REMOVED)));
                    }
                }
            });
        }).subscribeOn(JavaFxScheduler.getInstance());
    }
    public static <T,R> Observable<ListChange<R>> fromObservableListDistinctMappings(final ObservableList<T> source, Func1<T,R> mapper) {

        return Observable.create((Observable.OnSubscribe<ListChange<R>>) subscriber -> {

            final DupeCounter<R> dupeCounter = new DupeCounter<>();
            source.stream().map(mapper::call).forEach(dupeCounter::add);

            source.addListener((ListChangeListener<T>) c -> {

                while (c.next()) {
                    if (c.wasAdded()) {
                        c.getAddedSubList().stream().map(mapper::call)
                                .filter(v -> dupeCounter.add(v) == 1)
                                .forEach(v -> subscriber.onNext(ListChange.of(v,Flag.ADDED)));
                    }
                    if (c.wasRemoved()) {
                        c.getRemoved().stream().map(mapper::call)
                                .filter(v -> dupeCounter.remove(v) == 0)
                                .forEach(v -> subscriber.onNext(ListChange.of(v,Flag.REMOVED)));
                    }
                }
            });
        }).subscribeOn(JavaFxScheduler.getInstance());
    }

    private static final class DupeCounter<T> {
        private final HashMap<T,Integer> counts = new HashMap<>();

        public int add(T value) {
            Integer prev = counts.get(value);
            int newVal = 0;
            if (prev == null) {
                newVal = 1;
                counts.put(value, newVal);
            }  else {
                newVal = prev + 1;
                counts.put(value, newVal);
            }
            return newVal;
        }
        public int remove(T value) {
            Integer prev = counts.get(value);
            if (prev != null && prev > 0) {
                int newVal = prev - 1;
                counts.put(value, newVal);
                return newVal;
            }
            else {
                throw new IllegalStateException();
            }
        }
    }
    public static final class ListChange<T> {
        private final T value;
        private final Flag flag;

        private ListChange(T value, Flag flag) {
            this.value = value;
            this.flag = flag;
        }
        public static <T> ListChange<T> of(T value, Flag flag) {
            return new ListChange<>(value, flag);
        }
        public T getValue() {
            return value;
        }
        public Flag getFlag() {
            return flag;
        }
        @Override
        public String toString() {
            return flag + " " + value;
        }
    }
    public enum Flag {
        ADDED,
        REMOVED,
        UPDATED;
    }
}
```

**Comment by thomasnield** [comment]
This feature seems to be impacted by the #27 issue. I need to resolve that first before I merge this one.

**Comment by thomasnield** [comment]
Great! Now that #28 has been resolved I can get back to the `ObservableList` factories. I just added them to `JavaFxObservable` and I'm starting to compose the unit tests.

**Comment by thomasnield** [comment]
Okay done! I just added the JavaDoc. If anybody wants to review and make any last-minute suggestions to the API, please let me know within the next 24 hours. After that I will probably put together a release.

Assuming the functionality of this library matures enough for a warranted a 1.0 release, I may start working on my [Kotlin extension to this library](https://github.com/thomasnield/RxKotlinFX).

**Comment by thomasnield** [comment]
Don't get too concerned with the failed unit test. I am sure this is the known issue in #22

**Pull request merged**
